# CONSTANTES FOR BASE MENU
MENU_PLAYERS = 1
MENU_TOURNAMENTS = 2
MENU_REPORTS = 3
MENU_EXIT = 4

# CONSTANTES FOR TOURNAMENT MENU
MENU_TOURNAMENT_CREATION = 1
MENU_TOURNAMENT_DISPLAY = 2
MENU_TOURNAMENT_START = 3
MENU_TOURNAMENT_RECOVERY = 4
MENU_TOURNAMENT_EXIT = 5
TOURNAMENT_LIST = []
NB_JOUEURS_BY_MATCH = 2

# CONSTANTES FOR REPORT MENU
MENU_REPORT_TOURNAMENT_PLAYERS = 1
MENU_REPORT_TOURNAMENT_SCORES = 2
MENU_REPORT_PLAYER_NAME = 3
MENU_REPORT_PLAYER_FNAME = 4
MENU_RESULT_TOURNAMENT_LIST = 5
MENU_RESULT_TOURNAMENT_DETAIL = 6
MENU_REPORT_EXPORT_HTML = 7
MENU_REPORT_EXIT = 8
REPORT_TABLE_WIDTH = 60
REPORT_MATCH_WIDTH = 18
REPORT_SCORE_WIDTH = REPORT_TABLE_WIDTH - REPORT_MATCH_WIDTH
PLAYER_MAX_LENGTH = 17

# CONSTANCES FOR PLAYER MENU
MENU_PLAYER_CREATION = 1
MENU_PLAYERS_DISPLAY = 2
MENU_PLAYERS_DELETE = 3
MENU_PLAYERS_EXIT = 4
PLAYER_LIST = []
# POS_PLAYER_SCORE = 7
# POS_PLAYER_UUID = 1
# MATCHS_LIST_TOURNAMENT = []
MATCHS_LIST = []
MATCH_ID_LIST = []
